name: a11y
on: [pull_request]

jobs:
  a11y:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - run: pnpm i -w
      - name: Run pa11y-ci (targets defined per app)
        run: pnpm a11y
