name: a11y

on:
  pull_request:

permissions:
  contents: read

jobs:
  a11y:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: ./.github/actions/setup-pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run pa11y-ci (targets defined per app)
        run: pnpm a11y
