name: ci
on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm i -w
      - name: Commitlint (PR commits)
        if: github.event_name == 'pull_request'
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: .commitlintrc.cjs
      - name: Semantic PR title
        if: github.event_name == 'pull_request'
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          headerPattern: '^(.+)$'
          headerPatternCorrespondence: type
          types: |
            .+
      - name: Turbo remote cache
        env:
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
        run: echo "Turbo cache configured"
      - run: pnpm lint
      - run: pnpm typecheck
      - name: SSR guard
        run: node scripts/assert-no-client.mjs
      - run: pnpm build
