name: ci

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: ./.github/actions/setup-pnpm
      - run: pnpm install --frozen-lockfile
      - name: Commitlint (PR commits)
        if: github.event_name == 'pull_request'
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: .commitlintrc.cjs
      - name: Semantic PR title
        if: github.event_name == 'pull_request'
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            build
            chore
            ci
            docs
            feat
            fix
            perf
            refactor
            revert
            style
            test
          subjectPattern: '^(?!\s*$).+'
          subjectPatternError: >-
            PR titles must include a short description (e.g. "Update pnpm setup configuration").
      - name: Turbo remote cache
        env:
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
        run: echo "Turbo cache configured"
      - run: pnpm lint:dark
      - run: pnpm lint
      - run: pnpm typecheck
      - name: SSR guard
        run: node scripts/assert-no-client.js
      - run: pnpm build
