name: db-migrate
on:
  push:
    branches: [main]
    paths: ["supabase/migrations/**"]
  workflow_dispatch:

jobs:
  migrate-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm
      - name: Setup pnpm
        run: |
          corepack enable
          corepack use pnpm@10.17.1
      - uses: supabase/setup-cli@v1
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Link staging
        run: supabase link --project-ref ${{ secrets.SUPABASE_STAGING_REF }}
      - name: Push migrations (staging)
        run: supabase db push --password ${{ secrets.SUPABASE_DB_PASSWORD_STAGING }}

  migrate-prod:
    needs: migrate-staging
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm
      - name: Setup pnpm
        run: |
          corepack enable
          corepack use pnpm@10.17.1
      - uses: supabase/setup-cli@v1
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Link prod
        run: supabase link --project-ref ${{ secrets.SUPABASE_PROD_REF }}
      - name: Push migrations (prod)
        run: supabase db push --password ${{ secrets.SUPABASE_DB_PASSWORD_PROD }}
