name: links
on: [pull_request]

jobs:
  links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: ./.github/actions/setup-pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run link checks
        run: pnpm links
